### ISSUE TITLE
Xml error with ampersands

### ISSUE THREAD

**Issue by oblab** [tristangoossens/php-sitemap-generator#2]
I had this error when i tried to generate the sitemap : $dom->loadXML($xml); EntityRef: expecting ';' at line 163
so i add this code, and now it's working well
`$xml = str_replace('&', '&amp;', $xml);`

**Comment by tristangoossens** [comment]
Thank you for submitting this issue!

If you would like to, you could open a pull request with your solution.

Tristan Goossens

**Comment by oblab** [comment]
done !

**Comment by tristangoossens** [comment]
Nice!

Dont forget to submit your changes in a pull request

**Comment by oblab** [comment]
yep, sorry i'm a beginner on github...

**Comment by tristangoossens** [comment]
I have merged your PR. Thank you again for opening this issue!
